var data = {
    "carray": [
        ["amaria", "a", 2],
        ["amaria", "b", 2],
        ["cornelia", "a", 2],
        ["cornelia", "b", 2],
    ],
    "characters": {
        "amaria": {
            "name": "amaria",
            "poses": {
                "a": {
                    "pose_path": "characters/amaria/a/",
                    "max_face_height": 205,
                    "face_path": "face",
                    "faces": ["0.png", "1.png"],
                    "outfit_path": "",
                    "default_outfit": "uniform/uniform.png",
                    "default_accessories": [["uniform/hair+1/off.png", "+1", 111]],
                    "default_left_crop": 170,
                    "default_right_crop": 446,
                    "default_top_crop": 28,
                    "outfits": [
                        ["casual/casual.png", [["casual/hair+1/off.png", "+1", 111]]],
                        ["casual/casual2.png", [["casual/hair+1/off.png", "+1", 111]]],
                        ["gym/gym.png", [["gym/hair+1/off.png", "+1", 111]]],
                        ["nude/nude.png", [["nude/hair+1/off.png", "+1", 111]]],
                        ["uniform/uniform.png", [["uniform/hair+1/off.png", "+1", 111]]],
                    ],
                },
                "b": {
                    "pose_path": "characters/amaria/b/",
                    "max_face_height": 205,
                    "face_path": "face",
                    "faces": ["0.png", "1.png"],
                    "outfit_path": "",
                    "default_outfit": "uniform/uniform.png",
                    "default_accessories": [["uniform/hair+1/off.png", "+1", 111]],
                    "default_left_crop": 255,
                    "default_right_crop": 446,
                    "default_top_crop": 28,
                    "outfits": [
                        ["casual/casual.png", [["casual/hair+1/off.png", "+1", 111]]],
                        ["casual_book/casual_book.png", [["casual_book/hair+1/off.png", "+1", 111]]],
                        ["gym/gym.png", [["gym/hair+1/off.png", "+1", 111]]],
                        ["nude/nude.png", [["nude/hair+1/off.png", "+1", 111]]],
                        ["uniform/uniform.png", [["uniform/hair+1/off.png", "+1", 111]]],
                    ],
                },
            },
        },
        "cornelia": {
            "name": "cornelia",
            "poses": {
                "a": {
                    "pose_path": "characters/cornelia/a/",
                    "max_face_height": 201,
                    "face_path": "face",
                    "faces": [
                        "0.webp",
                        "1.webp",
                        "2.webp",
                        "3.webp",
                        "4.webp",
                        "5.webp",
                        "6.webp",
                        "7.webp",
                        "8.webp",
                        "9.webp",
                        "10.webp",
                        "11.webp",
                        "12.webp",
                        "13.webp",
                        "14.webp",
                        "15.webp",
                        "16.webp",
                        "17.webp",
                        "18.webp",
                        "19.webp",
                        "20.webp",
                        "21.webp",
                        "22.webp",
                    ],
                    "outfit_path": "",
                    "default_outfit": "gym2.webp",
                    "default_accessories": [],
                    "default_left_crop": 70,
                    "default_right_crop": 363,
                    "default_top_crop": 6,
                    "outfits": [
                        ["gym.webp", []],
                        ["gym2.webp", []],
                    ],
                },
                "b": {
                    "pose_path": "characters/cornelia/b/",
                    "max_face_height": 217,
                    "face_path": "mutations/twintails/face",
                    "faces": [
                        "twintails/face/0.webp",
                        "twintails/face/1.webp",
                        "twintails/face/2.webp",
                        "twintails/face/3.webp",
                        "twintails/face/4.webp",
                        "twintails/face/5.webp",
                        "twintails/face/6.webp",
                        "twintails/face/7.webp",
                        "twintails/face/8.webp",
                        "twintails/face/9.webp",
                        "twintails/face/10.webp",
                        "twintails/face/11.webp",
                        "twintails/face/12.webp",
                        "twintails/face/13.webp",
                        "twintails/face/14.webp",
                        "twintails/face/15.webp",
                        "twintails/face/16.webp",
                        "twintails/face/17.webp",
                        "twintails/face/18.webp",
                        "twintails/face/19.webp",
                        "twintails/face/20.webp",
                        "twintails/face/21.webp",
                        "twintails/face/22.webp",
                        "twintails/face/23.webp",
                        "twintails/face/24.webp",
                        "twintails/face/25.webp",
                        "twintails/face/26.webp",
                        "twintails/face/27.webp",
                        "twintails/face/28.webp",
                        "twintails/face/29.webp",
                        "twintails/face/30.webp",
                        "twintails/face/31.webp",
                        "twintails/face/32.webp",
                        "twintails/face/33.webp",
                        "twintails/face/34.webp",
                    ],
                    "outfit_path": "",
                    "default_outfit": "uniform/uniform.webp",
                    "default_accessories": [["uniform/ponytail/off.webp", "0", 200]],
                    "default_left_crop": 14,
                    "default_right_crop": 425,
                    "default_top_crop": 14,
                    "outfits": [["uniform/uniform.webp", [["uniform/ponytail/off.webp", "0", 200]]]],
                },
            },
        },
    },
};
