#TODO: Add date to logs
version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(levelname)s - %(asctime)s - %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
  detailed:
    format: "[%(levelname)-8s|%(module)-15s|L%(lineno)-5d] %(asctime)s: %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
    level: INFO
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: serverConfig/logs/process_zip_files_log.log
    maxBytes: 10485760
    backupCount: 10
loggers:
  process_zip_files:
    level: DEBUG
    handlers: [console, file]
